### ISSUE TITLE
Nan value at loss calculation

### ISSUE THREAD

**Issue by DanHalp** [shivram1987/AdaNorm#1]
At diffGradNorm.py (I guess of all of them, as they are identical) wherever we have a division, we must add the epsilon (e.g. 1e-8) - otherwise it would result for me with NaNs.

![image](https://user-images.githubusercontent.com/92723917/209700600-aef0aae9-a000-4cf2-8220-18d5d675a8e5.png)

**Comment by DanHalp** [comment]
or .add_(group['eps'])

**Comment by shivram1987** [comment]
Thanks for the observation. 
denom = exp_avg_sq.sqrt().add_(group['eps']) is already added to avoid this problem in the update rule.

Adding it in grad1 = grad * exp_grad_norm / grad_norm might not be required as for any batch of data, the network will always generate some gradient, hence the grad_norm would be always a positive number.

However, if you get Nan problem, then better to include add_(group['eps']) to avoid this problem, as you have suggested.
